//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PavilionApp.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pavilionDBEntities : DbContext
    {
        public pavilionDBEntities()
            : base("name=pavilionDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Arendators> Arendators { get; set; }
        public virtual DbSet<Occupancy> Occupancy { get; set; }
        public virtual DbSet<TradeList> TradeList { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Pavilions> Pavilions { get; set; }
    }
}
