//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PavilionApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Occupancy
    {
        public int ID_occupancy { get; set; }
        public int ID_rent_host { get; set; }
        public string Name { get; set; }
        public double ID_Employee { get; set; }
        public string Pavilion { get; set; }
        public string Status { get; set; }
        public System.DateTime Start_Occupancy { get; set; }
        public System.DateTime End_Occupancy { get; set; }
    
        public virtual Arendators Arendators { get; set; }
        public virtual Users Users { get; set; }
    }
}
