//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PavilionApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pavilions
    {
        public string Name_TM { get; set; }
        public string PavilionNumber { get; set; }
        public int FloorNumber { get; set; }
        public double MetrPrice { get; set; }
        public double AddedValue { get; set; }
        public double Area { get; set; }
        public string StatusPavilion { get; set; }
    }
}
