//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PavilionApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradeList
    {
        public string NameTrade { get; set; }
        public string Status { get; set; }
        public int PavilionsCount { get; set; }
        public string City { get; set; }
        public string PriceBuilding { get; set; }
        public double AddedValueTrade { get; set; }
        public int floor { get; set; }
        public byte[] imageTrade { get; set; }
    }
}
